apiVersion: v1

kind: ResourceQuota

metadata:
  name: vote-quota
  namespace: vote

spec:
    hard:
      pods: "15"
      requests.cpu: "2"
      requests.memory: "2Gi"
      limits.cpu: "4"
      limits.memory: "4Gi"


